---
- hosts: nodo1
  become: yes
  tasks:
    - name: instalar mariadb
      apt: name={{ item }} state=installed update_cache=yes
      with_items:
        - mariadb-server
        - python-mysqldb 

    - name: copiar bbdd wordpress
      copy: 
	src: templates/bbddwordpress.sql 
	dest: /tmp
      
    - name: restaurar bbdd wordpress
      mysql_db: 
	name: wordpress	
	state: import 
	target: /tmp/bbddwordpress.sql

    - name: crear usuario
      mysql_user: 
	name: wordpress 
	password: wordpress 
	priv: wordpress.*:ALL 
	host: %

    - name: configuracion mariadb
      copy: 
	src: templates/50-server.cnf 
	dest: /etc/mysql/mariadb.conf.d/50-server.cnf

  handlers:
  - name: reinicio mysql
    service: name=mysql state=restarted
