---
- hosts: nodo2
  become: yes
  tasks:
    - name: descomprimir wordpress en nodo2
      unarchive: 
        src: templates/wordpress-4.9.2-es_ES.zip 
        dest: /var/www/html  
        owner: www-data
        group: www-data

    - name: copiar wp-config
      template: 
        src: templates/wp-config.php 
        dest: /var/www/html/wp-config.php
        owner: www-data
        group: www-data

    - name: reiniciar nginx
      service: name=nginx state=restarted
      become: yes

    - name: reiniciar fpm
      service: name=php7.0-fpm state=restarted
      become: yes
