---
- hosts: nodo2
  become: yes
  tasks:
    - name: instalar nginx
      apt: name=nginx update_cache=yes

    - name: copiar configuracion nginx
      copy: 
        src: templates/default 
        dest: /etc/nginx/sites-available/


  handlers:
  - name: reinicio nginx
    service: name=nginx state=restarted

