---
- hosts: nodo2
  become: yes
  tasks:
    - name: descomprimir wordpress en nodo2
      unarchive: 
        src: templates/wordpress-4.9.2-es_ES.zip 
        dest: /var/www/html  
        owner: www-data
        group: www-data

    - name: copiar wp-config
      template: 
        src: templates/wp-config.php 
        dest: /var/www/html/wordpress/
        owner: www-data
        group: www-data

