---
- hosts: nodo1
  become: yes
  tasks:
    - name: instalar bind9
      apt: name=bind9 update_cache=yes


    - name: Añadiendo fichero cofiguración bind9
      copy:      
        src: templates/named.conf.local
        dest: /etc/bind/named.conf.local

    - name: Configurando zona directa
      copy:
        src: templates/db.example.com
        dest: /var/cache/bind/db.example.com

    - name: Configurando zona inversa
      copy:
        src: templates/db.100.16.172
        dest: /var/cache/bind/db.100.16.172

    - name: restart bind9
      become: yes
      service:
        name: bind9
        state: restarted

  handlers:
  - name: reinicio bind9
    service: name=bind9 state=restarted
